#!/bin/bash

# Prints out the volume percentage

VOLUME_ON_ICON=''

get_volume(){
        volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
        echo "$VOLUME_ON_ICON  $volume%"
}

get_volume
